version: "3.9"

networks:
  nginx-net:
    external:
      name: nginx-net

services:
  frontend:
    build: .
    restart:
      always
    ports:
      - "6543:6543"
    networks:
      - nginx-net
    environment:
      VIRTUAL_HOST: nl-reasoner.fabraham.dev,fabraham.dev
      LETSENCRYPT_HOST: nl-reasoner.fabraham.dev,fabraham.dev
      LETSENCRYPT_EMAIL: mail@fabraham.dev